
defaults:
  - _self_
  - model_type: ae
  - data: data
  - models: ae
  - training: ae
  - tuning: ae
  - thresholding: ae
  #- override hydra/launcher: joblib

random_state: 42
experiment_name: anomaly_detection

tracking:
  enabled: true
  #uri: "sqlite:///mlflow.db"





#hydra:
#  launcher:
#    n_jobs: 2