model_space:
  n_layers:
    name: n_layers
    low: 1
    high: 3

  encoder_dim:
    name: enc_dim
    low: 16
    high: 128


training_space:
  lr:
    name: lr
    low: 1e-4
    high: 1e-2
    log: true

  batch_size:
    name: batch_size
    choices: [32, 64, 128]

  epochs: 10