prep:
  scaler:
    names: [standard, minmax]

  dimensionality:
    enabled: true
    names:
      - pca
      - truncated_svd
    n_components:
      low: 1
      high: 8



model_space:
  n_estimators:
    name: n_estimators
    type: int
    low: 50
    high: 300

  contamination:
    name: contamination
    type: float
    low: 0.01
    high: 0.2